<?php


namespace app\admin\controller;


use think\Controller;
use think\Db;
use think\Request;

class Category extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }
    public function add(){
        // 1. 权限
        if (!$this->request->isPost()){
            return json([
                'code'=>400,
                'msg'=>'请求方式错误'
            ]);
        }
        $data = $this->request->post();
        $validate = validate('Category');
        if (!$validate->check($data)){
            return json([
                'code'=>404,
                'msg'=>$validate->getError()
            ]);
        }
        $result = Db::table('category')->insert($data);

        if($result){
            return json([
                'code'=>200,
                'msg'=>'分类添加成功'
            ]);
        }else{
            return json([
                'code'=>400,
                'msg'=>'分类添加失败'
            ]);
        }
    }
    public function index(){
        $data = $this->request->get();
        if (isset($data['page']) && !empty($data['page'])){
            $page =$data['page'];
        }else{
            $page = 1;
        }
        if (isset($data['limit']) && !empty($data['limit'])){
            $limit =$data['limit'];
        }else{
            $limit = 5;
        }
        $where=[];
        if (isset($data['cname']) && !empty($data['cname'])){
           $where['cname']=['like','%'.$data.'%'];
        }

//        id   city

        $category= Db::table('category')->field('cid,cname,cdesc')->order('cid','asc')->where($where)->page($page)->limit($limit)->select();
        $count = Db::table('category')->where($where)->count();
        if ($category && $count){
            return json([
                'code'=>200,
                'msg'=>'数据获取成功',
                'data'=>$category,
                'total'=>$count
            ]);
        }else{
            return json([
                'code'=>200,
                'msg'=>'数据获取失败'
            ]);
        }

    }
    public function save(){
        $data = $this->request->post();
        $validate = validate('category');
        $cid = $data['cid'];
        unset($data['cid']);
        $result=Db::table('category')->where('cid',$cid)->update($data);
        if ($result){
            return json([
                'code'=>200,
                'msg'=>'数据更新成功'
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'数据更新失败'
            ]);
        }
    }
    public function delete(){

    }
    public function update($id)
    {
        $data = $this->request->put();
        return json([
            'code'=>200,
            'msg'=>'删除成功',
            'data'=>$data
        ]);
    }
    public function indexall(){
        $data = $this->request->get();
        if (isset($data['page']) && !empty($data['page'])){
            $page =$data['page'];
        }else{
            $page = 1;
        }
        if (isset($data['limit']) && !empty($data['limit'])){
            $limit =$data['limit'];
        }else{
            $limit = 5;
        }
        $where=[];
        if (isset($data['cname']) && !empty($data['cname'])){
            $where['cname']=['like','%'.$data.'%'];
        }
        $category= Db::table('category')->field('cid,cname,cdesc')->where($where)->page($page)->limit($limit)->select();
        $count = Db::table('category')->where($where)->count();
        if ($category && $data){
            return json([
                'code'=>200,
                'msg'=>'数据获取成功',
                'data'=>$category,
                'total'=>$count
            ]);
        }else{
            return json([
                'code'=>200,
                'msg'=>'数据获取失败'
            ]);
        }
    }
    public function read($id){
        $category= Db::table('category')->field('cid,cname,cdesc')->where('cid',$id)->select();
        return json([
            'code'=>200,
            'msg'=>'数据获取成功',
            'data'=>$category
        ]);
    }
}